left_hand:
  - L_thumb_proximal_yaw_joint
  - L_thumb_proximal_pitch_joint
  - L_thumb_intermediate_joint
  - L_thumb_distal_joint
  - L_index_proximal_joint
  - L_index_intermediate_joint
  - L_middle_proximal_joint
  - L_middle_intermediate_joint
  - L_ring_proximal_joint
  - L_ring_intermediate_joint
  - L_pinky_proximal_joint
  - L_pinky_intermediate_joint
right_hand:
  - R_thumb_proximal_yaw_joint
  - R_thumb_proximal_pitch_joint
  - R_thumb_intermediate_joint
  - R_thumb_distal_joint
  - R_index_proximal_joint
  - R_index_intermediate_joint
  - R_middle_proximal_joint
  - R_middle_intermediate_joint
  - R_ring_proximal_joint
  - R_ring_intermediate_joint
  - R_pinky_proximal_joint
  - R_pinky_intermediate_joint
